backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads" # where uploaded files are saved
public_folder: "/uploads"      # how uploaded files are served in browser

media_library:
  name: uploadcare

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
